### ISSUE TITLE
Review 결과

### ISSUE THREAD

**Issue by LDY0912** [LeEHaNa1/test-repo#5]
확인 후 수정 바람
1299acc

**Comment by LeEHaNa1** [comment]
예전에 수업 들으면서 한 파일 내에 여러 예제들을 푸느랴 주석 처리하면서 푼 걸 그대로 올린 것 같아요. history에는 삭제된 여러 코드가 보이는데 지금은 코드 한 개 제외하고는 삭제된 상태입니다!
